### ISSUE TITLE
Rename `continue_if_empty` to `validate_if_empty` and default to true

### ISSUE THREAD

**Issue by larsnystrom** [zendframework/zend-inputfilter#12]
The configuration parameter `continue_if_empty` in `Zend\InputFilter\Input` doesn't convey much meaning. Continue doing what? The name has no apparent link to the validation process, where it is an essential parameter. 

I also think it should default to `true`. Because of #11 I marked a field with `required == false` and added a `NotEmpty` validator instead, and later found out that the validator didn't run. What's the point of a `NotEmpty` validator if it doesn't run when the value is empty?

**Comment by weierophinney** [comment]
The idea behind `continue_if_empty` was "continue validating even if the value is empty." I'm in agreement with you that renaming it might make it more clear. However, doing so would also be a substantial BC break.

My suggestion is that if we do this, we do it as follows:

- Next minor release:
  - Rename `continueIfEmpty` property to `validateIfEmpty`.
  - Introduce `setValidateIfEmpty()` method; it will manipulate the `validateIfEmpty` flag.
  - Introduce `validateIfEmpty()` method; it will return the `validateIfEmpty` flag.
  - Rewrite `setContinueIfEmpty()` to proxy to `setValidateIfEmpty()` and raise an `E_USER_DEPRECATED` error indicating the latter method should be used instead.
  - Rewrite `continueIfEmpty()` to proxy to `validateIfEmpty()` and raise an `E_USER_DEPRECATED` error indicating the latter method should be used instead.
  - Update `Zend\InputFilter\Factory` to:
    - on detection of `continue_if_empty` in a specification, raise an `E_USER_DEPRECATED` error indicating that `validate_if_empty` should be used instead; have it pass the value to `setValidateIfEmpty()`.
    - detect `validate_if_empty` in a specification and pass it to `setValidateIfEmpty()`.
  - Update an logic internally that uses the `*continueIfEmpty` methods to use the new methods.
- Next major release:
  - Remove the deprecated methods and support for the deprecated key.

Any takers?

**Comment by weierophinney** [comment]
I'm noting this as a BC Break. Even if we follow the above, by marking a method as deprecated, we *will* break some applications. (In particular, I know that when Apigility users have display_errors enabled, this breaks the payloads returned.) However, it *is* BC-safe, as the original methods are preserved, and a migration path is offered which will remove the errors.

**Comment by larsnystrom** [comment]
That seems reasonable. What do you think of the change of default value?

**Comment by weierophinney** [comment]
@larsnystrom The default value needs to stay as-is; changing it would be a very large BC break.

Additionally, there are other factors at play here.

Currently, `allow_empty` and `continue_if_empty` are false by default, and `required` is true. This combination does injects a `NotEmpty` validator to the top of the ValidatorChain setup to break on error (i.e., if it fails, no more validators are executed); the validation chain is then executed, and, if the value is empty, the input is marked as invalid.

The solution to #11 is to keep the input as required, but to inject your own NotEmpty validator at the top of the chain yourself; `Input` will detect that it's present, and not inject its own NotEmpty validator.

**Comment by akrabat** [comment]
FWiW, I'm completely against changing the default even if it wasn't a BC break. If I have an empty field and required is false, I really don't want it validating against a StringLength.

**Comment by weierophinney** [comment]
@akrabat no worries; as noted above, we cannot, as it ignores the current workflow. :)

**Comment by larsnystrom** [comment]
@weierophinney I submitted #14 concerning my specific issue with the `NotEmpty` validator. If #14 is solved, I'm happy to keep the default as is.

**Comment by Maks3w** [comment]
Finally this options are declared deprecated now and will be removed. It's better if the user inject the NotEmpty validator when he wants.
