### ISSUE TITLE
Avoiding the default NotEmpty::IS_EMPTY validation message.

### ISSUE THREAD

**Issue by nathanjosiah** [zendframework/zend-inputfilter#124]
I have a form extending `Zend\Form\Form` implementing the `Zend\InputFilter\InputFilterProviderInterface`. One of my elements in my form is a `Radio` with some values and in my `InputFilterProvider` spec I have a `NotEmpty` validator with a custom message. Then, in my view I am using the `FormRadio` view helper to render the element which of course, also renders errors. 

The problem, is that if the user submits the form witout selecting a radio option, my validators are not used and instead the default `isEmpty` message is used from the `NotEmpty` validator. There is no way to bypass or customize this as the logic prevents any other use. Either, [it doesn't have a value but isn't required, or it doesn't have a value, is required, and then fails with the default message](https://github.com/zendframework/zend-inputfilter/blob/master/src/Input.php#L406-L415). Neither works for my use case as the message is not very nice to the user.

Unless I'm going to check for the default message or manually set the error when it isn't valid in my controller, I'm not sure what the best course of action is aside from making a PR that adds some type of customization to both `Input` and the factory.

**Comment by froschdesign** [comment]
@nathanjosiah 
Sorry for the late response!

Please try the following:

```php
$form = new Zend\Form\Form();
$form->add(
    [
        'name' => 'foo',
        'type' => Zend\Form\Element\Radio::class,
    ]
);
$inputFilter = new Zend\InputFilter\InputFilter();
$inputFilter->add(
    [
        'name'       => 'foo',
        'validators' => [
            [
                'name'    => Zend\Validator\NotEmpty::class,
                'options' => [
                    'messages' => [
                        Zend\Validator\NotEmpty::IS_EMPTY => 'My empty message!',
                    ],
                ],
            ],
        ],
    ]
);
$form->setInputFilter($inputFilter);
$form->setData([]);
$form->isValid();
var_dump($form->getMessages());
```
This outputs:
```
array (size=1)
  'foo' => 
    array (size=1)
      'isEmpty' => string 'My empty message!' (length=17)
```

**Comment by froschdesign** [comment]
@nathanjosiah 
Thanks for the feedback!
