### ISSUE TITLE
ConfigProvider - registration of InputFilterAbstractServiceFactory

### ISSUE THREAD

**Issue by vaclavvanik** [zendframework/zend-inputfilter#129]
As of written in [docs](https://zendframework.github.io/zend-inputfilter/specs/#setup) `InputFilterAbstractServiceFactory` has to be registered in ConfigProvider.

Correct version of invoke is imho:

```
    public function __invoke()
    {
        return [
            'dependencies' => $this->getDependencyConfig(),
            'input_filters' => [
                'abstract_factories' => [
                    InputFilterAbstractServiceFactory::class,
                ],
            ],
        ];
    }
```

**Comment by codeaid** [comment]
Came to report the same issue after spending half an hour trying to understand why is nothing visible in my `input_filter_specs` key.
