### ISSUE TITLE
[php 7.2] incompatible prototype

### ISSUE THREAD

**Issue by remicollet** [zendframework/zend-inputfilter#140]
Yes, quite "early" report ;)

`PHP Fatal error:  Declaration of Zend\InputFilter\CollectionInputFilter::isValid() must be compatible with Zend\InputFilter\BaseInputFilter::isValid($context = NULL) in ...`

**Comment by Slamdunk** [comment]
https://github.com/zendframework/zend-inputfilter/pull/142

**Comment by froschdesign** [comment]
Fixed with #142
