### ISSUE TITLE
 Fatal error: Class 'Zend\ServiceManager\AbstractPluginManager' not found in D:\XAMPP\htdocs\sn\zend-mail\vendor\zendframework\zend-mail\src\Protocol\SmtpPluginManager.php on line 20

### ISSUE THREAD

**Issue by sakinaaf** [zendframework/zend-inputfilter#186]
Fatal error: Class 'Zend\ServiceManager\AbstractPluginManager' not found in D:\XAMPP\htdocs\sn\zend-mail\vendor\zendframework\zend-mail\src\Protocol\SmtpPluginManager.php on line 20

**Comment by froschdesign** [comment]
Duplicate of zendframework/zend-mail#233
