### ISSUE TITLE
setMessages not working properly

### ISSUE THREAD

**Issue by googlle** [zendframework/zend-inputfilter#19]
Hello.

I tried to validate my form.
In controller I use this code
```php
if ($formUrl != $url) {
	$form->get('url')->setMessages(array('Link is wrong'));
}

if ($form->isValid()) {
	echo 'validate';
}
```
If I set "setMessages" - form is validate, but form must not be validate

**Comment by Maks3w** [comment]
You should open the issue on https://github.com/zendframework/zend-form/issues
