### ISSUE TITLE
'Value is required' message should be localizable

### ISSUE THREAD

**Issue by tflin** [zendframework/zend-inputfilter#28]
We had the issue that 'Value is required' message can not be localized to Chinese as it is hardcoded in the framework code. The custom-message NotEmpty validator cannot override this error message in our case. Please help to make the hardcoded message localizable.

**Comment by Maks3w** [comment]
> @weierophinney said: Does this resolve the issue with the NotEmpty messages that have occurred since 2.4? It seems like we should set it in the same format, using the same key, in order to retain the previous behavior?

From #24

**Comment by weierophinney** [comment]
Fixed with #61

**Comment by stefanotorresi** [comment]
@weierophinney i'm afraid it actually isn't, see #67
