### ISSUE TITLE
Rename InputFilterPluginManager as PluginManager

### ISSUE THREAD

**Issue by Maks3w** [zendframework/zend-inputfilter#34]
It's redundant to repeat component name in class name.

This large class name produces inconsistent method names in consumer classes (see `Factory::setInputFilterManager`)

**Comment by gianarb** [comment]
:+1:

**Comment by weierophinney** [comment]
Regardless of whether or not this is targeted at 3.0, is still a BC break, and should be labeled as such, as the change has ramifications:

- users interacting with it directly have to make changes to their code
- references to the class in service manager configurations will need to be updated

One reason to potentially keep the name is that this is one plugin manager that often is referenced with others in the same connect: validator, filter, and form plugin managers. Keeping the name prevents the necessity of aliasing when these are referenced together.

**Comment by Maks3w** [comment]
I did remove the BC break label because this can be done in bc way and do the removal of the old class on v3

**Comment by Maks3w** [comment]
This is a naming convention so I agree with that.
