### ISSUE TITLE
Filter to boolean and non-required input

### ISSUE THREAD

**Issue by fust** [zendframework/zend-inputfilter#99]
I noticed some strange behaviour today:

```php
$input= new \Zend\InputFilter\Input();
$input->setValue("0");
$input->getFilterChain()->attachByName('boolean');
$input->setRequired(false);
	    
$input->isValid(); //return false
```

The input gets filtered to a boolean value (false) before being validated. Because both allowEmpty and continueIfEmpty are false by default the NotEmpty validator is attached to the validator chain. The value "false" gets passed to the NotEmpty validator which, correctly, marks it as "invalid".

This results in strange "This field is required...." messages after validation on non-required inputs, while boolean false is a perfectly valid, non-empty value for e.g. a checkbox element.

**Comment by Maks3w** [comment]
Its better set allowEmpty and continueIfEmpty as true and attach the NonEmpty validator if you need.

```php
$input = new Input();
$input->setAllowEmpty(true);         // Disable BC Break logic related to treat `null` values as valid empty value instead *not set*.
$input->setContinueIfEmpty(true);    // Disable BC Break logic related to treat `null` values as valid empty value instead *not set*.
$input->getValidatorChain()->attach(
    new Zend\Validator\NotEmpty(),
    true                             // break chain on failure

);
```

**Comment by fust** [comment]
I agree it's best to disable the BC break logic on new code.
However, it's not desireable to modify dozens (or even hundreds in enterprise applications) of existing forms/filters after an update to the framework just because the input filter logic itself is broken.
Especially when this can be fixed in a future release.

**Comment by Maks3w** [comment]
It can't be fixed.
